### ISSUE TITLE
which version does tensorflow to use

### ISSUE THREAD

**Issue by sparkssjj** [viplix3/PointPillars-TF#1]
hi which version does tensorflow to use

**Comment by viplix3** [comment]
Hi @sparkssjj
This repo is just some bug fixes/additional functionality over the [original GitHub repo](https://github.com/tyagi-iiitv/PointPillars)

As the original GitHub repo did not list any specific TensorFlow version, I ended up using TensorFlow v2.4.1
You can try the same and update if that works for you.

**Comment by whzz101** [comment]
when i load the model. it error
2022-01-14 11:11:53,115 - [INFO]: Loading model from path: ./logs/model.h5
Traceback (most recent call last):
  File "point_pillars_inference.py", line 150, in <module>
    load_model_and_run_inference(pred_config)
  File "point_pillars_inference.py", line 52, in load_model_and_run_inference
    pillar_net.load_weights(configs.model_path)
  File "/data/zhou.zhou/project_envs/P16_PointPillars/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/data/zhou.zhou/project_envs/P16_PointPillars/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1373, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/data/zhou.zhou/project_envs/P16_PointPillars/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 691, in load_weights_from_hdf5_group
    str(len(weight_values)) + ' elements.')
ValueError: Layer #2 (named "cnn/block1/conv2d0" in the current model) was found to correspond to layer cnn/block1/conv2d0 in the save file. However the new layer cnn/block1/conv2d0 expects 1 weights, but the saved weights have 2 elements.
