### ISSUE TITLE
load model.h5 failed

### ISSUE THREAD

**Issue by whzz101** [viplix3/PointPillars-TF#2]
hi, when i load the model. it error, i use master version
2022-01-14 11:11:53,115 - [INFO]: Loading model from path: ./logs/model.h5
Traceback (most recent call last):
File "point_pillars_inference.py", line 150, in
load_model_and_run_inference(pred_config)
File "point_pillars_inference.py", line 52, in load_model_and_run_inference
pillar_net.load_weights(configs.model_path)
File "/data/zhou.zhou/project_envs/P16_PointPillars/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
return super(Model, self).load_weights(filepath, by_name)
File "/data/zhou.zhou/project_envs/P16_PointPillars/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1373, in load_weights
saving.load_weights_from_hdf5_group(f, self.layers)
File "/data/zhou.zhou/project_envs/P16_PointPillars/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 691, in load_weights_from_hdf5_group
str(len(weight_values)) + ' elements.')
ValueError: Layer #2 (named "cnn/block1/conv2d0" in the current model) was found to correspond to layer cnn/block1/conv2d0 in the save file. However the new layer cnn/block1/conv2d0 expects 1 weights, but the saved weights have 2 elements.

**Comment by viplix3** [comment]
@whzz101 please try using the weights provided in [this link](https://drive.google.com/file/d/1-ygz7RpTH7Fpd-8cKV8-v1OUVxKxJEIK/view?usp=sharing)

**Comment by whzz101** [comment]
ok，3q，i try it

**Comment by whzz101** [comment]
> @whzz101 please try using the weights provided in [this link](https://drive.google.com/file/d/1-ygz7RpTH7Fpd-8cKV8-v1OUVxKxJEIK/view?usp=sharing)

ok，3q，i test it, it works!
