### ISSUE TITLE
got a ValueError when load weights

### ISSUE THREAD

**Issue by sparkssjj** [viplix3/PointPillars-TF#3]
hi, when i load the pretrain weights, i got a incompatible error.
----------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "point_pillars_inference.py", line 196, in <module>
    load_model_and_run_inference(pred_config)
  File "point_pillars_inference.py", line 56, in load_model_and_run_inference
    pillar_net.load_weights(configs.model_path)
  File "/PointPillars-TF-master/pp_tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2234, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/PointPillars-TF-master/pp_tf/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 710, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/PointPillars-TF-master/pp_tf/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/PointPillars-TF-master/pp_tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3706, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/PointPillars-TF-master/pp_tf/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 891, in assign
    (tensor_name, self._shape, value_tensor.shape))
ValueError: Cannot assign to variable loc/conv2d/kernel:0 due to variable shape (1, 1, 384, 12) and value shape (18, 384, 1, 1) are incompatible

**Comment by viplix3** [comment]
@sparkssjj can you try the weights provided in the issue: https://github.com/viplix3/PointPillars-TF/issues/2

**Comment by sparkssjj** [comment]
@viplix3 yes, i tried, when i use tensorflow==1.15, i can load the weights but can not print the inferecne results. when i use tensorflow==2.4.0 i got the imcompatible error.

**Comment by viplix3** [comment]
@sparkssjj weights shared in #2  might be of some older variant.
I'll try training a new model and share the weights if possible.

A similar issue is addressed in #5, hence I will be closing this.
