### ISSUE TITLE
ValueError: Failed to find data adapter that can handle input: <class 'processors.SimpleDataGenerator'>, <class 'NoneType'>

### ISSUE THREAD

**Issue by wrli20** [viplix3/PointPillars-TF#4]
Hey Bro,

Something wrong happened in processors, the follow is the info:

Traceback (most recent call last):
  File "point_pillars_training_run.py", line 102, in <module>
    train_PillarNet(train_configs)
  File "point_pillars_training_run.py", line 81, in train_PillarNet
    pillar_net.fit(training_gen,
  File "/home/ross/pyProject/PointPillars-TF/env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ross/pyProject/PointPillars-TF/env/lib/python3.8/site-packages/keras/engine/data_adapter.py", line 984, in select_data_adapter
    raise ValueError(
ValueError: Failed to find data adapter that can handle input: <class 'processors.SimpleDataGenerator'>, <class 'NoneType'>

I will appreciate it if u can check it out.

**Comment by viplix3** [comment]
Hi @wrli20, apologies for the late reply.

I am not maintaining this repository anymore so expect delayed responses.
The latest commit of the master branch should resolve your issue.
