### ISSUE TITLE
Unable to open model.h5 file and the pretrained model link is not opening

### ISSUE THREAD

**Issue by anarghyaraghav** [viplix3/PointPillars-TF#6]
Obtaining this error while training the model.  
 ****python point_pillars_training_run.py**** 

FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = './logs/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Unable to open the google drive link for pretrained model.

**Comment by viplix3** [comment]
Hi @anarghyaraghav, the training script [checks if the model is available](https://github.com/viplix3/PointPillars-TF/blob/9d0704c073d5b3330b11b97ce86c85571ed90e15/point_pillars_training_run.py#L46), if it is, only then the model is loaded, else a new model is trained from random weights.

Given the logic, the error you've mentioned shouldn't occur when executing the training script, unless I'm missing something, in which case if would be helpful if you could provide some more context.

I've provided a partially trained model [here](https://github.com/viplix3/PointPillars-TF/blob/9d0704c073d5b3330b11b97ce86c85571ed90e15/model_data/model.h5).

You can try running inference using that model if you'd like.

**Comment by anarghyaraghav** [comment]
Hi  @viplix3 
Following are the steps that I followed:

1.  Cloned the repository
2. Downloaded the KITTI dataset
3.  Run the  **python setup.py install**
4. Installed the packages numpy , tensorflow, tensorflow_probability, scikit-learn.
5. Trained the model  python point_pillars_training_run.py 


Obtained following error:
python point_pillars_training_run.py
 error :
Traceback (most recent call last):
  File "point_pillars_training_run.py", line 26, in <module>
    pillar_net.load_weights(os.path.join(MODEL_ROOT, "model.h5"))
  File "/datadrive/ar/env2/PointPillars/env1/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/datadrive/ar/env2/PointPillars/env1/lib/python3.8/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/datadrive/ar/env2/PointPillars/env1/lib/python3.8/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = './logs/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Please let me know if you need any additional details.
